/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as TestApiRouteImport } from './routes/test-api'
import { Route as CatalogoSlugRouteImport } from './routes/catalogo.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TestApiRoute = TestApiRouteImport.update({
  id: '/test-api',
  path: '/test-api',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoSlugRoute = CatalogoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CatalogoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/test-api': typeof TestApiRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/test-api': typeof TestApiRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/test-api': typeof TestApiRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalogo' | '/dashboard' | '/test-api' | '/catalogo/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogo' | '/dashboard' | '/test-api' | '/catalogo/$slug'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/dashboard'
    | '/test-api'
    | '/catalogo/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  TestApiRoute: typeof TestApiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-api': {
      id: '/test-api'
      path: '/test-api'
      fullPath: '/test-api'
      preLoaderRoute: typeof TestApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$slug': {
      id: '/catalogo/$slug'
      path: '/$slug'
      fullPath: '/catalogo/$slug'
      preLoaderRoute: typeof CatalogoSlugRouteImport
      parentRoute: typeof CatalogoRoute
    }
  }
}

interface CatalogoRouteChildren {
  CatalogoSlugRoute: typeof CatalogoSlugRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoSlugRoute: CatalogoSlugRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRouteWithChildren,
  DashboardRoute: DashboardRoute,
  TestApiRoute: TestApiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
